# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: sh-checker
        # You may pin to the exact commit or the version.
        # uses: luizm/action-sh-checker@c6edb3de93e904488b413636d96c6a56e3ad671a
        uses: luizm/action-sh-checker@v0.8.0
        with:
          # Directory or file name that doesn't need to be checked
          #sh_checker_exclude: # optional
          # If true, it will skip the shfmt. Default is false
          #sh_checker_shfmt_disable: # optional
          # If true, it will skip the shellcheck. Default is false
          #sh_checker_shellcheck_disable: # optional
          # If true, run checkbashisms tool against scripts. Default is false
          #sh_checker_checkbashisms_enable: # optional, default is false
          # If true, it will show the errors as commentaries in the pull requests. Default is false
          sh_checker_comment: true
          # If true, run only on files changed in the PR branch. Default is false
          #sh_checker_only_diff: # optional
                
